name: GitHub pages

on:
  workflow_dispatch:
  pull_request:
    types:
        - closed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build docs
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./client/src
          output_dir: ./docs
          config_file: jsdoc.json
          template: docdash
          front_page: README.md
          
      - name: Upload docs
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: ./docs